### ISSUE TITLE
63a > Sec7 Security > Table 3 文言欠落

### ISSUE THREAD

**Issue by kthrtty** [openid-foundation-japan/800-63-4-draft#15]
https://github.com/openid-foundation-japan/800-63-4/blob/863ec12dc5dbb6bbd9b4e03a88ebec628fdabf2b/_sp800-63a/sec7_security.ja.md?plain=1#L88

`CSP implements out-of-band engagement (e.g., enrollment codes).`

に対応する訳がスキップされている

**Comment by nov** [comment]
pull req please.
